name: point_pillar_early_fusion
root_dir: "/media/amdin/Seagate Backup Plus Drive/lrs/Multi-V2X"
dataset_format: 'multi-v2x'

yaml_parser: "load_point_pillar_params"
train_params:
  batch_size: &batch_size 2
  epoches: 15
  eval_freq: 1
  save_freq: 1
  max_cav: 5

pr_setting:
  value: 0.1  # target penetration rate
  path: "./opencood/hypes_pr/pr_config_list_15k.json"

fusion:
  core_method: 'EarlyFusionDataset' # LateFusionDataset, EarlyFusionDataset, IntermediateFusionDataset supported
  args: []

# preprocess-related
preprocess:
  # options: BasePreprocessor, VoxelPreprocessor, BevPreprocessor
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.4, 0.4, 6]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
    num_point_features: &num_point_feats 4  # 3: xyz; 4: xyzi
  # lidar range for each individual cav.
  cav_lidar_range: &cav_lidar [-140.8, -40, -3, 140.8, 40, 3]
  # simulate lidar intensity
  intensity_simulation_method: 'carla'

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]

  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]

  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# anchor box related
postprocess:
  core_method: 'VoxelPostprocessor' # VoxelPostprocessor, BevPostprocessor supported
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: [3.90, 4.50, 6.25, 2.00, 1.60, 0.37, 3.90, 4.50, 6.25, 2.00, 1.60, 0.37]  # [car, van, truck, motor, cycle, walker]
    w: [1.60, 2.10, 2.40, 0.80, 0.37, 0.37, 1.60, 2.10, 2.40, 0.80, 0.37, 0.37]
    h: [1.56, 2.00, 2.10, 1.10, 1.18, 1.86, 1.56, 2.00, 2.10, 1.10, 1.18, 1.86]
    r: [0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 90.0, 90.0, 90.0, 90.0, 90.0, 90.0]
    # l: 3.90
    # w: 1.60
    # h: 1.56
    # r: [0, 90]
    num: &achor_num 12
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.20
  order: 'hwl' # hwl or lwh
  max_num: 100 # maximum number of objects in a single frame. use this number to make sure different frames has the same dimension in the same batch
  nms_thresh: 0.15

# model related
model:
  core_method: point_pillar
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *achor_num
    num_point_features: *num_point_feats  # must specified
    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      num_features: 64

    base_bev_backbone:
      layer_nums: [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]

    anchor_num: *achor_num

loss:
  core_method: point_pillar_loss
  args:
    cls_weight: 1.0
    reg: 2.0

optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep #step, multistep and Exponential support
  gamma: 0.1
  step_size: [10, 15]

