[build-system]
# requires = ["setuptools>=41.0", "wheel", "pccm>=0.2.21"]
requires = ["setuptools==58.0.4", "wheel==0.37.1", "pccm==0.3.4", "pybind11==2.9.1", "ccimport==0.3.7", "fire==0.4.0"]
build-backend = "setuptools.build_meta"
